### ISSUE TITLE
How to fix that?

### ISSUE THREAD

**Issue by takermodders** [daemon32/tickrate_enabler#1]
g++ -m32 -std=gnu++11 -fpermissive -fPIC -Dstrnicmp=strncasecmp -Dstricmp=strcasecmp -D_vsnprintf=vsnprintf -D_alloca=alloca -Dstrcmpi=strcasecmp -DPOSIX -DLINUX -D_LINUX -march=native -O2 -I/root/alliedmodders/hl2sdk-css/public -I/root/alliedmodders/hl2sdk-css/public/tier0 -I/root/alliedmodders/hl2sdk-css/public/tier1 -I/root/alliedmodders/mmsource-1.10/core -c serverplugin_empty.cpp
In file included from /root/alliedmodders/hl2sdk-css/public/tier1/utlvector.h:23:0,
                 from /root/alliedmodders/hl2sdk-css/public/tier1/convar.h:21,
                 from /root/alliedmodders/hl2sdk-css/public/eiface.h:16,
                 from serverplugin_empty.cpp:11:
/root/alliedmodders/hl2sdk-css/public/tier1/utlmemory.h: In constructor ‘CUtlMemoryAligned<T, nAlignment>::CUtlMemoryAligned(int, int)’:
/root/alliedmodders/hl2sdk-css/public/tier1/utlmemory.h:771:96: warning: there are no arguments to ‘_aligned_malloc’ that depend on a template parameter, so a declaration of ‘_aligned_malloc’ must be available [-fpermissive]
gcc -o Tickrate_Enabler.so -shared -m32 -L/root/alliedmodders/hl2sdk-css/lib/linux serverplugin_empty.o /root/alliedmodders/mmsource-1.10/build/core/metamod.2.css/sourcehook_sourcehook*.o \
	-ltier0_srv -ltier1_i486 -static-libstdc++ -lm -ldl
/usr/bin/ld: cannot find -ltier1_i486
collect2: error: ld returned 1 exit status
make: *** [Tickrate_Enabler.so] Error 1
root@debian:~/alliedmodders/tickrate_enabler#

**Comment by daemon32** [comment]
Firstly, you should never build random projects as root
Secondly, $(HL2SDK)/lib/linux (which is /root/alliedmodders/hl2sdk-css/lib/linux on your system) must have a library named 'tier1_i486' in it.
