### ISSUE TITLE
GetTickInterval returned bogus tick interval

### ISSUE THREAD

**Issue by MendusKun** [daemon32/tickrate_enabler#2]
GetTickInterval returned bogus tick interval (0.000000)[0.001000 to 0.100000 is valid range]

**Comment by daemon32** [comment]
Which engine reported this?

**Comment by MendusKun** [comment]
tf2

**Comment by daemon32** [comment]
Are you using a binary that accepts the '-tickrate' parameter? If so, please provide the full commandline for the server in question.

**Comment by MendusKun** [comment]
-game tf -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +map ${defaultmap} +sv_setsteamaccount ${gslt} +servercfgfile ${servercfg} -maxplayers ${maxplayers} -pidfile tf.pid -nobots +sv_pure 0 -nohltv -tvdisable +sv_allow_voice_from_file 0 -tickrate 100
https://forums.alliedmods.net/showthread.php?t=293340
# psychonic :
```
Double-post, but whatever.
The plugin likely just needs to be recompiled to take into account the ICommandLine change in 9/2016. The last Release on the Github page is from 1/2016.
```

**Comment by MendusKun** [comment]
Will you fix it?
I can provide you with a server for the test

**Comment by rumblefrog** [comment]
+1, I'm having the same issue, and I'm running this on Linux with SM 1.8 - build 6115.
