### ISSUE TITLE
Dosent load on CSGO

### ISSUE THREAD

**Issue by DJPlaya** [daemon32/tickrate_enabler#3]
Failed to load plugin: (Failed to get API).
Meta 1.10.7-dev on CS:GO Latest WIN
:/

**Comment by daemon32** [comment]
This is not a metamod plugin, it is a [valve server plugin.](https://developer.valvesoftware.com/wiki/Server_plugins)

**Comment by DJPlaya** [comment]
Failed to load plugin "addons/Tickrate_Enabler_200tick"
Unable to load plugin "addons/Tickrate_Enabler_200tick"

Just saying, ime to busy to debug this now
